url: "https://inbyte.me"
baseurl: ""

title: "Inbit Me - Invitaciones Digitales"
description: "Invitaciones digitales e interactivas para casamientos, cumpleaños, eventos empresariales y sociales."
keywords:
  - "invitaciones"
  - "invitations"
  - "digital"
  - "casamiento"
  - "wedding"
  - "cumpleaños"
  - "birthday"
  - "party"

social:
  email: "hey@inbyte.me"
  instagram: "InbitMe"
  whatsapp: "+5493413114710"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
