url: "https://inbyte.me"
baseurl: ""

title: "Inbyte - Invitaciones Digitales"
description: "Invitaciones digitales e interactivas para casamientos, cumpleaños, eventos empresariales y sociales."
keywords:
  - "invitaciones"
  - "invitations"
  - "digital"
  - "casamiento"
  - "wedding"
  - "cumpleaños"
  - "birthday"
  - "party"
  
social:
  email: "hey@inbyte.me"

exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
